config/routes.rb
Rails.application.routes.draw do
  resources :challenges, :path => 'c', :param => :slug, :except => [:index] do
    resources :enrollments, only: [:create, :destroy]
    resources :statuses, :path => 's', :except => [:show, :index] do
      resources :likes, only: [:create, :destroy]
      resources :comments, :except => [:show, :index]
    end
  end

  # Not a typo
  resources :categories, :path => 'challenges', :param => :slug, :only => [:index, :show]

  devise_for :user, :path => '', :path_names => { :sign_in => 'login',
                                                  :sign_out => 'logout',
                                                  :sign_up => 'signup', }

  resource :user, :path => 'a', :only => [:edit, :profile] do
    collection do
      get 'profile'
      patch 'update_profile'
      patch 'update_email_and_password'
    end
  end
  get '/:username' => 'users#show', :as => 'profile'

  authenticated :user do
    root 'users#homepage', as: :authenticated_root
  end
  root 'static#index'

  scope '/premium' do
    get 'info' => 'premium#index', :as => 'premium'
    post 'create' => 'premium#create', :as => 'premium_create'
    get 'success' => 'premium#success', :as => 'premium_success'
    get 'cancel' => 'premium#cancel', :as => 'premium_cancel'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Relationships
  has_many :challenges, :dependent => :destroy
  has_many :statuses, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  has_many :enrollments, :dependent => :destroy

  # Validation rules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable,
         :validatable, authentication_keys: [:login]
  attr_writer :login

  validates :email,
            :length => { :maximum => 100 },
            # Real email address format
            :format => { :with => /\A[^@ ]+@[^@ ]+\.[^@ ]+\Z/ },
            :uniqueness => { :case_sensitive => false }

  validates :password,
            :presence => true,
            :password_strength => true,
            :on => :create

  validates :username,
            :presence => true,
            :length => { :maximum => 15, :minimum => 3 },
            # Alphanumeric username, dashes allowed but not at the start
            :format => { :with => /\A[a-z0-9][a-z0-9_-]{0,24}\z/ },
            :uniqueness => { :case_sensitive => false }

  validates :bio,
            :length => { :maximum => 300 }

  # For security & trust reasons
  BANNED_USERNAMES = ['admin', 'administrator', 'contact', 'fraud', 'guest',
     'help', 'hostmaster', 'committi', 'mailer-daemon', 'moderator',
     'moderators', 'nobody', 'postmaster', 'root', 'security', 'support',
     'sysop', 'webmaster', 'enable', 'new', 'signup', 'premium',].freeze

  validates_each :username do |record, attr, value|
    if BANNED_USERNAMES.include?(value.to_s.downcase)
      record.errors.add(attr, 'is not permitted')
    end
  end

  # Helpers
  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication warden_condition
    conditions = warden_condition.dup
    login = conditions.delete(:login)
    where(conditions).where(
      ['lower(username) = :value OR lower(email) = :value',
      { value: login.strip.downcase },]).first
  end

  def avatar_url(user, opts = {})
    size = opts[:size || 32]
    hash = Digest::MD5.hexdigest(user.email.downcase)
    "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}&d=identicon&r=PG"
  end

  delegate :count, to: :statuses, prefix: true

  delegate :count, to: :comments, prefix: true

  def likes_counter(user)
    Like.where(status: Status.where(user: user)).count
  end

  def best_streak_overall(user)
    Enrollment.where(user: user).order('best_streak DESC').first.best_streak
  end

  def matching?(current_user, user)
    current_user == user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :profile, :update, :destroy,
                                  :update_email_and_password, :update_profile,]

  def show
    @user = User.find_by(username: params[:username])
    @comment = Comment.new
  end

  def homepage
    @user = current_user
  end

  def edit; end

  def profile; end

  def update_profile
    if @user.update(profile_params)
      redirect_to profile_path(@user.username)
    else
      render :profile
    end
  end

  def update_email_and_password
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      redirect_to profile_path(@user.username)
    else
      render :edit
    end
  end

  def destroy; end

  def set_user
    @user = current_user
  end

private

  def profile_params
    params.require(:user).permit(:username, :bio)
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_account_feed.html.erb
<% @user.statuses.order("created_at").reverse.each do |status| %>
  <div class="row">
    <div class="col-2 text-center mt-4">
      <%= image_tag @user.avatar_url(status.user, size: "80x80!"), :class => "avatar" %>
      <p>
        <%= link_to status.user.username, profile_path(status.user.username), :class => "text-black breakword" %>
        <% if status.user.is_premium? %>
          <%= link_to premium_path, :class => "link-primary" do %>
            <i class="bi bi-check-circle small"></i>
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="col">
      <div class="card mb-3 shadow-lg mb-5 bg-body rounded">
        <div class="card-header p-4 text-secondary">
          Posté sur <%= link_to status.challenge.title, challenge_path(status.challenge.slug) %>,
          il y a <%= time_ago_in_words status.created_at %>
        </div>
        <div class="pt-4 px-4 status">
          <%= simple_format(status.content) %>
          <% unless status.image.attachment.nil? %>
              <%= image_tag status.image, :class => "card-img border border-2" %>
          <% end %>
        </div>

        <div class="d-flex justify-content-around mt-4 pb-4">

          <% if user_signed_in? && liked?(status, current_user) %>
            <%= link_to challenge_status_like_path(status.challenge, status, Like.find_by(user: current_user, status: status)), method: "delete", :class => "btn btn-link text-danger nodecoration" do %>
              <i class="bi bi-heart-fill"></i> <%= status.likes.count %>
            <% end %>
          <% elsif user_signed_in? %>
            <%= link_to challenge_status_likes_path(status.challenge, status), method: "post", :class => "btn btn-link text-black nodecoration" do %>
              <i class="bi bi-heart"></i> <%= status.likes.count %>
            <% end %>
          <% else %>
            <div class="btn btn-link text-black nodecoration">
              <i class="bi bi-heart-fill"></i> <%= status.likes.count %>
            </div>
          <% end %>

          <a class="btn btn-link text-black nodecoration" data-bs-toggle="collapse" href="#c<%= status.id %>" role="button" aria-expanded="false" aria-controls="#c<%= status.id %>">
            <i class="bi bi-chat"></i> <%= status.comments.count %>
          </a>

          <% if has_rights?(status.user) %>
            <div class="btn-group dropup">
              <button type="button" class="btn btn-link dropdown-toggle nodecoration text-black emptydrop" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-box-arrow-in-up lg-ico"></i>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Supprimer", challenge_status_path(status.challenge.slug, status), data: { confirm: "Are you sure?" }, :class => "text-danger dropdown-item", method: :delete %></li>
                <li><%= link_to "Modifier", edit_challenge_status_path(status.challenge.slug, status), :class => "text-black dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
            <button type="button" class="btn btn-link nodecoration text-white emptydrop" disabled>
              <i class="bi bi-box-arrow-in-up"></i>
            </button>
          <% end %>
        </div>

        <div class="collapse" id="c<%= status.id %>">
          <% if user_signed_in? %>
            <div class="my-3 px-4">
              <%= form_with(model: [status.challenge, status, @comment], local: true) do |form| %>
                <%= form.text_area :content, :class => "form-control mb-3" %>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <%= form.submit "Envoyer", :class => "btn btn-primary btn-right" %>
                </div>
              <% end %>
            </div>
          <% else %>
            <p class="my-3 px-4 pb-4">
              <%= link_to "Connectez-vous", new_user_session_path %> pour envoyer un commentaire
            </p>
          <% end %>
          <% if status.comments.count > 0 %>
            <% status.comments.order("created_at").each do |comment| %>
              <hr />
              <div class="row px-4 pb-4">
                <div class="col-2 text-center">
                  <%= image_tag @user.avatar_url(comment.user, size: "80x80!"), :class => "avatar mt-2" %>
                </div>
                <div class="col">
                  <p class="text-secondary">
                    <%= link_to comment.user.username, profile_path(comment.user.username) %>
                    ·
                    <%= time_ago_in_words comment.updated_at %>
                  </p>
                  <div class="comment">
                    <%= simple_format(comment.content) %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_account_summary.html.erb
<h2>Statistiques</h2>

<div class="row g-2">
  <div class="col stats">
    <div class="card border border-1 text-center">
      <div class="card-body">
        <span class="h4"><%= @user.likes_counter(@user) %></span><br />
        Likes
      </div>
    </div>
  </div>
  <div class="col stats">
    <div class="card border border-1 text-center">
      <div class="card-body">
        <span class="h4"><%= @user.statuses_count %></span><br />
        Status
      </div>
    </div>
  </div>
  <div class="col stats">
    <div class="card border border-1 text-center">
      <div class="card-body">
        <span class="h4"><%= @user.comments_count %></span><br />
        Commentaires
      </div>
    </div>
  </div>
  <div class="col stats">
    <div class="card border border-1 text-center">
      <div class="card-body">
        <span class="h4">
          <% if @user.enrollments.any? %>
            <%= @user.best_streak_overall(@user) %>
          <% else %>
            0
          <% end %>
        </span><br />
        Meilleure série
      </div>
    </div>
  </div>
</div>

<h2 class="mt-4">Challenges que vous administrez</h2>
<% if @user.challenges.count == 0 %>
  <p>Vous n’administrez challenge. <%= link_to "Créez-en un !", new_challenge_path %></p>
<% else %>
  <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-2 flex-wrap d-flex align-items-stretch">
  <% @user.challenges.each do |challenge| %>
    <div class="col">
      <div class="card border border-1">
        <div class="card-header px-4 py-3">
          <%= link_to challenge_path(challenge.slug), :class => "link-dark h4" do %>
            <%= challenge.title %>
          <% end %><br />
          <span class="text-muted">Challenge <%= t(challenge.interval) %></span>
            <p class="pt-2">
            <%= link_to "Modifier", edit_challenge_path(challenge.slug), :class => "link-danger" %>
            </p>
        </div>
          <div class="card-body text-center">
            <p><%= challenge.subtitle %></p>
            <div class="d-flex justify-content-around">

              <div>
                <span class="h4"><%= challenge.enrollments.count %></span><br />
                Participants
              </div>
              <div>
                <span class="h4"><%= challenge.statuses.count %></span><br />
                Status
              </div>
            </div>
          </div>
      </div>
    </div>
  <% end %>
  </div>
<% end %>

<h2 class="mt-4">Challenges auxquels vous participez</h2>

<div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-2 flex-wrap d-flex align-items-stretch">
  <% @user.enrollments.each do |enrollment| %>
    <div class="col">
      <div class="card border border-1">
        <div class="card-header px-4 py-3">
          <%= link_to challenge_path(enrollment.challenge.slug), :class => "link-dark h4" do %>
            <%= enrollment.challenge.title %>
          <% end %>
          <p class="text-secondary pt-2">
            Challenge <%= t(enrollment.challenge.interval) %><br />
            par <%= link_to enrollment.challenge.user.username, profile_path(enrollment.challenge.user.username) %>
            <% if enrollment.challenge.user.is_premium? %>
              <%= link_to premium_path, :class => "link-primary" do %>
                <i class="bi bi-check-circle small"></i>
              <% end %>
            <% end %>
          </p>
        </div>
        <div class="card-body text-center">
          <p><%= enrollment.challenge.subtitle %></p>
          <div class="d-flex justify-content-around flex-wrap">
            <div>
              <span class="h4"><%= enrollment.challenge.enrollments.count %></span><br />
              Participants
            </div>
            <div>
              <span class="h4"><%= enrollment.challenge.statuses.count %></span><br />
              Status
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_bio.html.erb
<% unless @user.bio.nil? %>
<div class="row flex-wrap">
  <div class="card mb-3 shadow-lg p-4 mb-5 bg-body rounded">
      <%= simple_format(@user.bio) %>
    </div>
  </div>
<% end %>

app/views/users/_navbar.html.erb
<div class="pageheader bg-white px-5 pt-5 mb-5">
  <div class="container mb-5">
    <h1 class="h3">
      <%= @user.username %>
      <% if @user.is_premium? %>
        <%= link_to premium_path, :class => "link-primary" do %>
          <i class="bi bi-check-circle small ms-2"></i>
        <% end %>
      <% end %>
    </h1>
    <p class="text-secondary">Membre depuis <%= time_ago_in_words @user.created_at %></p>
  </div>
  <div class="container pb-2">
    <ul class="d-flex justify-content-around nav">
      <% if @user.matching?(current_user, @user) %>
        <li>
        <% if current_page?(authenticated_root_path) %>
          <%= link_to "Vos challenges", authenticated_root_path, :class => "nav-link active" %>
        <% else %>
          <%= link_to "Vos challenges", authenticated_root_path, :class => "nav-link link-dark" %>
        <% end %>
        </li>
      <% end %>
      <li>
      <% if current_page?(profile_path(@user.username)) %>
      <%= link_to "Profil", profile_path(@user.username), :class => "nav-link active" %>
      <% else %>
      <%= link_to "Profil", profile_path(@user.username), :class => "nav-link link-dark" %>
      <% end %>
      </li>
      <% if @user.matching?(current_user, @user) %>
      <li><%= link_to "Éditer votre profil", profile_user_path, :class => "nav-link link-dark" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="my-5">Changer vos informations de compte</h1>
<div class="card mb-3 shadow-lg p-3 mb-5 bg-body rounded">
  <%= form_for(@user, :url => { :action => "update_email_and_password" } ) do |form| %>
    <%= form.label :email %><br />
    <%= form.email_field :email, :autocomplete => "email", :class => "form-control mb-3 card-header"  %>
    <%= form.label :password, "Password" %>
    <%= form.password_field :password, :autocomplete => "off", :class => "form-control mb-3 card-header"  %>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :class => "form-control mb-3 card-header" %>
    <%= form.label :current_password, :class => "mandatory" %> <i>(pour confirmer vos changements)</i><br />
    <%= form.password_field :current_password, :class => "form-control mb-3 card-header" %>
    <%= form.submit :class => "btn btn-primary mb-2 action_container", :id => "btn-formulary" %>
  <% end %>
</div>

<h3 class="mt-3">Cancel my account</h3>
<p>Unhappy? <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, :class => "btn btn-outline-danger", method: :delete %></p>

app/views/users/homepage.html.erb
<%= render "navbar.html" %>
<%= render "account_summary.html" %>

app/views/users/profile.html.erb
<h1 class="my-5">Changer vos informations de profil</h1>
<div class="card mb-3 p-5 shadow p-3 mb-5 bg-body rounded">
  <%= form_for(@user, :url => { :action => "update_profile" } ) do |form| %>
  <%= form.label "Username" %>
  <%= form.text_field :username, :class => "form-control mb-3 card-header" %>
  <%= form.label "Bio" %>
  <%= form.text_area :bio, :class => "form-control mb-3 card-header" %>
  <%= form.submit "Update", :class => "btn btn-primary mb-2", :id => "btn-formulary" %>
<% end %>
<p>Changez votre avatar sur <%= link_to "Gravatar", "https://gravatar.com/" %></p>
<%= link_to "Préférences du compte", edit_user_path %>
<%= link_to "Back", :back %>

app/views/users/show.html.erb
<%= render "navbar.html" %>

<%= render "bio.html" %>
<%= render "account_feed.html" %>