config/routes.rb
Rails.application.routes.draw do
  resources :challenges, :path => 'c', :param => :slug, :except => [:index] do
    resources :enrollments, only: [:create, :destroy]
    resources :statuses, :path => 's', :except => [:show, :index] do
      resources :likes, only: [:create, :destroy]
      resources :comments, :except => [:show, :index]
    end
  end

  # Not a typo
  resources :categories, :path => 'challenges', :param => :slug, :only => [:index, :show]

  devise_for :user, :path => '', :path_names => { :sign_in => 'login',
                                                  :sign_out => 'logout',
                                                  :sign_up => 'signup', }

  resource :user, :path => 'a', :only => [:edit, :profile] do
    collection do
      get 'profile'
      patch 'update_profile'
      patch 'update_email_and_password'
    end
  end
  get '/:username' => 'users#show', :as => 'profile'

  authenticated :user do
    root 'users#homepage', as: :authenticated_root
  end
  root 'static#index'

  scope '/premium' do
    get 'info' => 'premium#index', :as => 'premium'
    post 'create' => 'premium#create', :as => 'premium_create'
    get 'success' => 'premium#success', :as => 'premium_success'
    get 'cancel' => 'premium#cancel', :as => 'premium_cancel'
  end
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  # Relationships
  belongs_to :user
  belongs_to :category
  has_many :statuses, :dependent => :destroy
  has_many :enrollments, :dependent => :destroy

  # Validation rules
  validates :title,
            :length => { :minimum => 5, :maximum => 50 }

  validates :slug, :title,
            :uniqueness => true

  validates :title, :subtitle,
            :presence => true,
            :length => { :maximum => 50 }

  validates :description,
            :length => { :maximum => 100_000 }

  VALID_INTERVAL = ['daily', 'weekly', 'monthly'].freeze
  TIME_REQUIRED = ['weekly', 'monthly'].freeze
  TIMELY_FREE = ['daily'].freeze

  validates_each :interval do |record, attr, value|
    unless VALID_INTERVAL.include?(value.to_s.downcase)
      record.errors.add(attr, 'is not permitted')
    end
  end

  validates :next_date, presence: { :if => lambda { TIME_REQUIRED.include?(self.interval) } }
  validates :next_date, absence: { :if => lambda { TIMELY_FREE.include?(self.interval) } }

  # Slug assigning
  after_create :update_slug
  before_update :assign_slug

  def update_slug
    update :slug => assign_slug
  end

  def create_slug
    slug = self.title.parameterize
    if slug.empty? || slug.length < self.title.length
      self.id
    else
      slug
    end
  end

private

  def assign_slug
    self.slug = create_slug
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  include ApplicationHelper
  include ChallengesHelper
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :has_rights?, only: [:edit, :update, :destroy]
  before_action :ownership, only: [:edit, :update, :destoy]

  def show
    @statuses = @challenge.statuses
    @status = Status.new
    @comment = Comment.new
    if signed_in?
      @enrollment = current_user.enrollments.find_by(challenge: @challenge)
    end
    if @challenge.interval == 'daily'
      @countdown = countdown_string
    else
      @countdown = countdown_string(@challenge.next_date)
    end
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @category = Category.find_by(slug: params[:category])
    @challenge = Challenge.create(user: current_user,
                                  title: params[:title],
                                  subtitle: params[:subtitle],
                                  description: params[:description],
                                  category: @category,
                                  interval: params[:interval],
                                  next_date: params[:next_date])
    if @challenge.save
      flash[:notice] = 'Nouveau challenge créé'
      redirect_to challenge_path(@challenge.slug)
    else
      flash[:alert] = 'Impossible de créer ce challenge'
      render :new
    end
  end

  def edit; end

  def update
    if @challenge.update(challenge_params)
      flash[:notice] = 'Challenge modifié'
      redirect_to challenge_path(@challenge.slug)
    else
      flash[:alert] = 'Votre challenge n’a pas pu être modifié'
      render :edit
    end
  end

  def destroy
    @challenge.destroy
    flash[:notice] = 'Challenge effacé'
    redirect_to root_path
  end

  def set_challenge
    @challenge = Challenge.find_by(slug: params[:slug])
    @user = @challenge.user
    @user_path = profile_path(@user.username)
  end

  def set_categories
    @categories = Category.all
  end

  def ownership
    return true if current_user.is_admin
    if current_user != @challenge.user
      redirect_back fallback_location: root_path,
                    alert: 'Vous ne pouvez pas faire cela'
    end
  end

private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :description, :category_slug)
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
  def countdown_string(next_date = nil)
    if next_date.nil?
      @seconds = (Time.now.utc.tomorrow.midnight - Time.now.utc).to_i
    else
      @seconds = (next_date.to_time - Time.now).to_i
    end
    return Time.at(@seconds).utc.strftime('%H:%M:%S') if @seconds < 86_400
    return Time.at(@seconds).utc.strftime('%dj. %H:%M:%S') if @seconds > 86_400
  end
end

app/views/challenges/_enrollment_button.html.erb
<p>
<% if user_signed_in? && enrolled?(@challenge, current_user) %>
  <%= link_to "Quitter le challenge", challenge_enrollment_path(@challenge, Enrollment.find_by(user: current_user, challenge: @challenge)), method: "delete", :class => "btn btn-outline btn-primary" %>
<% elsif user_signed_in? %>
  <%= link_to "Rejoindre le challenge", challenge_enrollments_path(@challenge), method: "post", :class => "btn btn-primary" %>
<% else %>
  <%= "#{@challenge.enrollments.count} challengers" %>
<% end %>
</p>

app/views/challenges/_feed.html.erb
<% @statuses.order("created_at").reverse.each do |status| %>
  <div class="row">
    <div class="col-2 text-center mt-4">
      <%= image_tag @user.avatar_url(status.user, size: "80x80!"), :class => "avatar" %>
      <p>
        <%= link_to status.user.username, profile_path(status.user.username), :class => "text-black breakword" %>
        <% if status.user.is_premium? %>
          <%= link_to premium_path, :class => "link-primary" do %>
            <i class="bi bi-check-circle small"></i>
          <% end %>
        <% end %>
      </p>
    </div>
    <div class="col">
      <div class="card mb-3 shadow-lg p-4 mb-5 bg-body rounded">
        <div class="status">
          <%= simple_format(status.content) %>
          <% unless status.image.attachment.nil? %>
            <%= image_tag status.image, :class => "card-img border border-2 mb-3" %>
          <% end %>
          <p class="text-secondary"> Il y a <%= time_ago_in_words status.created_at %></p>
        </div>

        <div class="d-flex justify-content-around mt-4">

          <% if user_signed_in? && liked?(status, current_user) %>
            <%= link_to challenge_status_like_path(@challenge, status, Like.find_by(user: current_user, status: status)), method: "delete", :class => "btn btn-link text-danger nodecoration" do %>
              <i class="bi bi-heart-fill"></i> <%= status.likes.count %>
            <% end %>
          <% elsif user_signed_in? %>
            <%= link_to challenge_status_likes_path(@challenge, status), method: "post", :class => "btn btn-link text-black nodecoration" do %>
              <i class="bi bi-heart"></i> <%= status.likes.count %>
            <% end %>
          <% else %>
            <div class="btn btn-link text-black nodecoration">
              <i class="bi bi-heart-fill"></i> <%= status.likes.count %>
            </div>
          <% end %>

          <a class="btn btn-link text-black nodecoration" data-bs-toggle="collapse" href="#c<%= status.id %>" role="button" aria-expanded="false" aria-controls="#c<%= status.id %>">
            <i class="bi bi-chat"></i> <%= status.comments.count %>
          </a>

          <% if has_rights?(status.user) %>
            <div class="btn-group dropup">
              <button type="button" class="btn btn-link dropdown-toggle nodecoration text-black emptydrop" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-box-arrow-in-up lg-ico"></i>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Supprimer", challenge_status_path(@challenge.slug, status), data: { confirm: "Are you sure?" }, :class => "text-danger dropdown-item", method: :delete %></li>
                <li><%= link_to "Modifier", edit_challenge_status_path(@challenge.slug, status), :class => "text-black dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
            <button type="button" class="btn btn-link nodecoration text-white emptydrop" disabled>
              <i class="bi bi-box-arrow-in-up"></i>
            </button>
          <% end %>
        </div>

        <div class="collapse" id="c<%= status.id %>">
          <% if user_signed_in? %>
            <div class="my-3">
              <%= form_with(model: [@challenge, status, @comment], local: true) do |form| %>
                <%= form.text_area :content, :class => "form-control mb-3" %>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <%= form.submit "Envoyer", :class => "btn btn-primary btn-right" %>
                </div>
              <% end %>
            </div>
          <% else %>
            <p class="my-3">
              <%= link_to "Connectez-vous", new_user_session_path %> pour envoyer un commentaire
            </p>
          <% end %>
          <% if status.comments.count > 0 %>
            <% status.comments.order("created_at").each do |comment| %>
              <hr />
              <div class="row">
                <div class="col-2 text-center">
                  <%= image_tag @user.avatar_url(comment.user, size: "80x80!"), :class => "avatar mt-2" %>
                </div>
                <div class="col">
                  <p class="text-secondary">
                    <%= link_to comment.user.username, profile_path(comment.user.username) %>
                    ·
                    <%= time_ago_in_words comment.updated_at %>
                  </p>
                  <div class="comment">
                    <%= simple_format(comment.content) %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/challenges/_status_form.html.erb
<% if user_signed_in? && enrolled?(@challenge, current_user) && can_post?(@challenge, current_user) %>
  <%= form_with(model: [@challenge, @status], local: true) do |form| %>
    <div class="my-3">
      <%= form.text_area :content, :rows => "3", :class => "form-control mb-3" %>
     <div class="d-grid gap-2 d-md-flex justify-content-md-end">
       <div class="img-upload">
         <%= form.label :image, :class => "btn btn-link nodecoration text-black" do %>
           <i class="bi bi-file-earmark-image lg-ico"></i>
         <% end %>
          <%= form.file_field :image, :class => "form-control" %>
        </div>
       <%= form.submit "Envoyer", :class => "btn btn-primary btn-right" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/challenges/_streaks_counter.html.erb
<% if user_signed_in? && enrolled?(@challenge, current_user) %>
  <% if @enrollment.streaks > 0 || @challenge.statuses.where(user: @user).count %>
    <p><span class="h5">Statistiques</span><br />
      <span>Status&nbsp;:&nbsp;<%= @challenge.statuses.where(user: current_user).count %></span><br />
      <span>Séries&nbsp;:&nbsp;<%= @enrollment.streaks %></span><br />
      <span>Meilleur&nbsp;:&nbsp;<%= @enrollment.best_streak %></span>
    </p>
  <% elsif @enrollment.streaks == 0 && @enrollment.best_streak == 0 %>
    <p>Vous n’avez aucune progression sur ce challenge.</p>
  <% end %>
<% end %>

app/views/challenges/edit.html.erb
<h1 class="mb-5 mt-2">Modifier votre challenge</h1>
<div class="mb-3 shadow-lg p-3 mb-5 bg-body rounded">
  <%= form_for(@challenge, :url => { :action => "update" } ) do |form| %>
  <%= form.label :title %><br />
  <%= form.text_field :title, :autocomplete => "title", :class => "form-control mb-3 card-header"  %>

  <%= form.label :subtitle %>
  <%= form.text_field :subtitle, :autocomplete => "subtitle", :class => "form-control mb-3 card-header"  %>

  <%= form.label :description %>
  <%= form.text_area :description, :class => "form-control mb-3 card-header" %>

  <%= form.submit :class => "btn btn-primary mb-2 action_container", :id => "btn-formulary" %>
<% end %>

<%= button_to "Détruire ce challenge", challenge_path(@challenge.slug), data: { confirm: "Are you sure?" }, :class => "btn btn-outline-danger", method: :delete %>

app/views/challenges/new.html.erb
<div class="d-flex card mb-3 shadow-lg p-3 my-5 bg-body rounded">
<h1 class="mb-5 mt-2">Créer un challenge</h1>
<%= form_with url: challenges_path, local: true do |form| %>
  <%= form.label "Titre du challenge", :class => "mandatory" %>
  <%= form.text_field :title, :class => "form-control mb-3 card-header" %>
  <%= form.label "Sous-titre du challenge", :class => "mandatory"%>
  <%= form.text_field :subtitle, :placeholder => "Faites une courte description", :class => "form-control mb-3 card-header" %>
  <%= form.label "Catégorie", :class => "mandatory" %>
  <%= form.collection_select :category, @categories, :slug, :name, { include_blank: false },  { class: "form-control form-select mb-3" } %>
  <%= form.label "Description du challenge" %>
  <%= form.text_area :description, :class => "form-control mb-3 card-header" %>

  <div class="mb-3">
    <%= form.label "Intervalle", :class => "mandatory" %>
    <% Challenge::TIMELY_FREE.each do |interval| %>
      <div class="form-check">
        <%= form.radio_button :interval, interval, :class => "form-check-input", "data-bs-toggle" =>"collapse", "data-bs-target" => ".date-selector.show" %>
        <%= form.label t(interval).capitalize, :class => "form-check-label" %>
      </div>
    <% end %>
    <% Challenge::TIME_REQUIRED.each do |interval| %>
      <div class="form-check">
      <%= form.radio_button :interval, interval, :class => "form-check-input", "data-bs-toggle" =>"collapse", "data-bs-target" => ".date-selector:not(.show)" %>
      <%= form.label t(interval).capitalize, :class => "form-check-label" %>
      </div>
    <% end %>
  </div>

  <div class="collapse date-selector">
    <div class="mb-3">
      <%= form.label "Prochaine échéance" %>
      <%= form.date_field :next_date, min: Date.tomorrow, :class => "form-control" %>
    </div>
  </div>

  <%= form.submit "Enregistrer", :class => "btn btn-primary mb-2", :id => "btn-formulary" %>
<% end %>

app/views/challenges/show.html.erb
<div class="pageheader bg-white px-5 pt-5 mb-5">
  <div class="container mb-5">
    <h1 class= "h3">
      <%= @challenge.title %><br />
    </h1>
    <h2 class="h5">
      <%= @challenge.subtitle %>
    </h2>
    <span class="text-muted">Challenge <%= t(@challenge.interval) %></span>
  </div>
  <div class="container">
    <div class="d-flex justify-content-around text-secondary pb-2">
      <div><%= @challenge.enrollments.count %> participants</div>
      <div><%= @statuses.count %> status</div>
    </div>
  </div>
</div>

<div class="row flex-wrap">
  <% unless @challenge.description.empty? %>
    <div class="card mb-3 shadow-lg p-4 mb-5 bg-body rounded">
      <%= simple_format(@challenge.description) %>
    </div>
  <% end %>
  <div class="col-9">
    <%= render "status_form.html" %>
    <%= render "feed.html" %>
  </div>
  <div class="col-3">
    <div class ="mb-3">
    <span class="h5">Échéance</span><br />
    <% if @challenge.interval == "daily" %>
      <%= distance_of_time_in_words_to_now Time.now.utc.tomorrow.beginning_of_day %>
    <% else %>
      <%= distance_of_time_in_words_to_now @challenge.next_date.to_time.utc %>
    <% end %>

    <% if !can_post?(@challenge, current_user) && enrolled?(@challenge, current_user) %>
      <p class="mt-2">Vous avez déjà participé à l’échéance en cours</p>
    <% end %>
    </div>

    <%= render "streaks_counter.html" %>
    <%= render "enrollment_button.html" %>
      <span class="h5">Challenge lancé par</span>
      <div class="my-3">
        <%= image_tag @user.avatar_url(@user, size: "80x80!"), :class => "avatar me-3" %>
        <%= link_to @user.username, @user_path %>
        <% if @user.is_premium? %>
          <%= link_to premium_path, :class => "link-primary" do %>
            <i class="bi bi-check-circle small"></i>
          <% end %>
        <% end %>
      </div>
      <% if has_rights? %>
        <%= link_to "Modifier ce challenge", edit_challenge_path(@challenge.slug), :class => "btn btn-primary" %>
      <% end %>
    </div>
</div>