config/routes.rb
Rails.application.routes.draw do
  resources :challenges, :path => 'c', :param => :slug, :except => [:index] do
    resources :enrollments, only: [:create, :destroy]
    resources :statuses, :path => 's', :except => [:show, :index] do
      resources :likes, only: [:create, :destroy]
      resources :comments, :except => [:show, :index]
    end
  end

  # Not a typo
  resources :categories, :path => 'challenges', :param => :slug, :only => [:index, :show]

  devise_for :user, :path => '', :path_names => { :sign_in => 'login',
                                                  :sign_out => 'logout',
                                                  :sign_up => 'signup', }

  resource :user, :path => 'a', :only => [:edit, :profile] do
    collection do
      get 'profile'
      patch 'update_profile'
      patch 'update_email_and_password'
    end
  end
  get '/:username' => 'users#show', :as => 'profile'

  authenticated :user do
    root 'users#homepage', as: :authenticated_root
  end
  root 'static#index'

  scope '/premium' do
    get 'info' => 'premium#index', :as => 'premium'
    post 'create' => 'premium#create', :as => 'premium_create'
    get 'success' => 'premium#success', :as => 'premium_success'
    get 'cancel' => 'premium#cancel', :as => 'premium_cancel'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # Relationships
  has_many :challenges

  # Validation rules
  # TODO(@romain): If the need arises, we should create proper categories
  # validation. For now, categories are manually created by the admins from the
  # console, there’s no User interaction with them for now.
  # Meanwhile, you can generate basic categories from lib/tasks/create_categories.rb
  # Adjust the script for your needs.

  # Slug assigning
  # TODO(@romain): See the comment above.
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_categories
  def index
    @challenges = Challenge.all
  end

  def show
    @category = Category.find_by(slug: params[:slug])
    @challenges = @category.challenges
  end

  def set_categories
    @categories = Category.all
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="pageheader bg-white px-5 pt-5 mb-5">
  <div class="container mb-5">
    <h1 class="h3">Les Challenges</h1>
  </div>
  <div class="container pb-2">
    <div class="nav-list text-center">
      <%= link_to "Tous", categories_path, :class => "active" %>
      <% @categories.each do |category| %>
        <%= link_to category.name, category_path(category.slug), :class => "link-dark" %>
      <% end %>
    </div>
  </div>
</div>

<%= render "layouts/challenges_cards" %>

app/views/categories/show.html.erb
<div class="pageheader bg-white px-5 pt-5 mb-5">
  <div class="container mb-5">
    <h1 class="h3">Les Challenges</h1>
  </div>
  <div class="container pb-2">
    <div class="nav-list text-center">
      <%= link_to "Tous", categories_path, :class => "link-dark" %>
      <% @categories.each do |category| %>
        <% if category.slug == params[:slug] %>
        <%= link_to category.name, category_path(category.slug), :class => "active" %>
        <% else %>
          <%= link_to category.name, category_path(category.slug), :class => "link-dark" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render "layouts/challenges_cards" %>