config/routes.rb
Rails.application.routes.draw do
  resources :challenges, :path => 'c', :param => :slug, :except => [:index] do
    resources :enrollments, only: [:create, :destroy]
    resources :statuses, :path => 's', :except => [:show, :index] do
      resources :likes, only: [:create, :destroy]
      resources :comments, :except => [:show, :index]
    end
  end

  # Not a typo
  resources :categories, :path => 'challenges', :param => :slug, :only => [:index, :show]

  devise_for :user, :path => '', :path_names => { :sign_in => 'login',
                                                  :sign_out => 'logout',
                                                  :sign_up => 'signup', }

  resource :user, :path => 'a', :only => [:edit, :profile] do
    collection do
      get 'profile'
      patch 'update_profile'
      patch 'update_email_and_password'
    end
  end
  get '/:username' => 'users#show', :as => 'profile'

  authenticated :user do
    root 'users#homepage', as: :authenticated_root
  end
  root 'static#index'

  scope '/premium' do
    get 'info' => 'premium#index', :as => 'premium'
    post 'create' => 'premium#create', :as => 'premium_create'
    get 'success' => 'premium#success', :as => 'premium_success'
    get 'cancel' => 'premium#cancel', :as => 'premium_cancel'
  end
end

app/views/layouts/_callout.html.erb
<% unless current_page?(root_path) || user_signed_in? || devise_controller? %>
  <div class="pageheader alert alert-primary alert-dismissible fade show mb-0 py-5" role="alert">
    <div class="container">
      <p class="h3">Bienvenue sur Committi</p>
      <p>Committi est un réseau social de défis communautaires.<br />
      <%= link_to "En savoir plus…", root_path %></p>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

<% unless notice.nil? %>
  <div class="pageheader alert alert-success alert-dismissible fade show mb-0 py-5" role="alert">
    <div class="container">
      <p><i class="bi bi-info-circle"></i> <%= notice %></p>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% unless alert.nil? %>
  <div class="pageheader alert alert-danger alert-dismissible fade show mb-0 py-5" role="alert">
    <div class="container">
      <p><i class="bi bi-exclamation-triangle-fill"></i> <%= alert %></p>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_challenges_cards.html.erb
  <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-2 flex-wrap d-flex align-items-stretch">
    <% @challenges.order("updated_at").reverse.each do |challenge| %>
      <div class="col">
        <div class="card border border-1">
          <div class="card-header px-4 py-3">
            <%= link_to challenge_path(challenge.slug), :class => "link-dark h4" do %>
              <%= challenge.title %>
            <% end %>
            <p class="text-secondary pt-2">
            Challenge <%= t(challenge.interval) %><br />
            par <%= link_to challenge.user.username, profile_path(challenge.user.username) %>
            <% if challenge.user.is_premium? %>
              <%= link_to premium_path, :class => "link-primary" do %>
                <i class="bi bi-check-circle small"></i>
              <% end %>
            <% end %>
            </p>
          </div>
          <div class="card-body text-center">
            <p><%= challenge.subtitle %></p>
            <div class="d-flex justify-content-around">
              <div>
                <span class="h4"><%= challenge.enrollments.count %></span><br />
                Participants
              </div>
              <div>
                <span class="h4"><%= challenge.statuses.count %></span><br />
                Status
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/layouts/_footer.html.erb
<footer id="footer" class="text-secondary">
  <div class="py-3">
    <hr />
  </div>
    <div class="row">
        <div class="col-sm-6 col-md-4 footer-navigation">
            <p class="company-name">Committi Co © 2021 </p>
        </div>
        <div class="col-sm-6 col-md-4 footer-contacts">
            <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                <p><span class="new-line-span">21 Revolution Street</span> Paris, France</p>
            </div>
            <div><i class="fa fa-phone footer-contacts-icon"></i>
                <p class="footer-center-info email text-start"> +1 555 123456</p>
            </div>
            <div><i class="fa fa-envelope footer-contacts-icon"></i>
                <p><a href="#" target="_blank" class="link-secondary">support@company.com</a></p>
            </div>
        </div>
        <div class="col-md-4 footer-about">
            <h4>About the company</h4>
            <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
            <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
        </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "committi", root_path, :class => "navbar-brand"%>
  <div class="collapse navbar-collapse" id="navbarToggle">
    <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropstart">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %>
          </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
          <li><%= link_to "Tous les challenges", categories_path, :class => "dropdown-item" %></li>
          <li><%= link_to "Nouveau challenge", new_challenge_path, :class => "dropdown-item" %></li>
          <li><%= link_to "committi premium", premium_path, :class => "dropdown-item" %></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to "Préférences", profile_user_path, :class => "dropdown-item" %></li>
           <li><%= link_to "Déconnexion", destroy_user_session_path, :class => "dropdown-item bg-danger", :method => "delete" %></li>
        </ul>
      </ul>
      </div>
    <% else %>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, :class => "nav-link", :type => "button"%>
        </li>
        <li class="nav-item">
          <%= link_to "Inscription", new_user_registration_path, :class => "nav-link", :type => "button"%>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Committi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/callout" %>

    <section class="main">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
  <%= render "layouts/footer" %>
</html>